<a href="https://colab.research.google.com/github/ishafayetul/Machine_Learning/blob/main/One_hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [ ]:
price_df=pd.read_csv("drive/MyDrive/Learning/ML/Dummy Variables & One Hot Encoding/homeprices.csv")

In [ ]:
price_df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

#Dummy Variable Method

In [ ]:
dummies=pd.get_dummies(price_df)
dummies

area   price  town_monroe township  town_robinsville  town_west windsor
0   2600  550000                     1                 0                  0
1   3000  565000                     1                 0                  0
2   3200  610000                     1                 0                  0
3   3600  680000                     1                 0                  0
4   4000  725000                     1                 0                  0
5   2600  585000                     0                 0                  1
6   2800  615000                     0                 0                  1
7   3300  650000                     0                 0                  1
8   3600  710000                     0                 0                  1
9   2600  575000                     0                 1                  0
10  2900  600000                     0                 1                  0
11  3100  620000                     0                 1                  0
12  3600  695000                     0                 1                  0

In [ ]:
dummies_df=dummies.drop(["town_west windsor"],axis="columns")

In [ ]:
dummies_df

area   price  town_monroe township  town_robinsville
0   2600  550000                     1                 0
1   3000  565000                     1                 0
2   3200  610000                     1                 0
3   3600  680000                     1                 0
4   4000  725000                     1                 0
5   2600  585000                     0                 0
6   2800  615000                     0                 0
7   3300  650000                     0                 0
8   3600  710000                     0                 0
9   2600  575000                     0                 1
10  2900  600000                     0                 1
11  3100  620000                     0                 1
12  3600  695000                     0                 1

In [ ]:
x=dummies_df.drop(["price"],axis="columns")
x

area  town_monroe township  town_robinsville
0   2600                     1                 0
1   3000                     1                 0
2   3200                     1                 0
3   3600                     1                 0
4   4000                     1                 0
5   2600                     0                 0
6   2800                     0                 0
7   3300                     0                 0
8   3600                     0                 0
9   2600                     0                 1
10  2900                     0                 1
11  3100                     0                 1
12  3600                     0                 1

In [ ]:
y=dummies_df.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [ ]:
model= linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [ ]:
model.predict([[3400,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [ ]:
model.predict([[2000,0,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([489257.68651905])

In [ ]:
model.score(x,y)

0.9573929037221872

#One Hot Encodding


In [115]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [116]:
dfle=price_df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [124]:
x = dfle[["town","area"]] #converting dataframe into 2D array cz 1HE expects 2D array
x

town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

In [125]:
y=dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [131]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories=[0])
x=ohe.fit_transform(x).toarray()
x

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [ ]:
x=x[:,1:]
x

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [ ]:
model.fit(x,y)

LinearRegression()

In [ ]:
model.predict([[0,1,3400]])

ValueError: X has 3 features, but LinearRegression is expecting 11 features as input.